name: Update Dashboard Data

on:
  schedule:
    - cron: '*/30 13-23 * * 1-5'
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: npm install
    
    - name: Fetch Google Sheets data
      env:
        GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
        GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
      run: node src/scripts/fetch-data.js
    
    - name: Check for data changes
      id: verify-changed-files
      run: |
        if git diff --quiet data/translations.json; then
          echo "changed=false" >> $GITHUB_OUTPUT
        else
          echo "changed=true" >> $GITHUB_OUTPUT
        fi
    
    - name: Commit and push if data changed
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/translations.json
        git commit -m "📊 Auto-update translation data $(date '+%Y-%m-%d %H:%M')"
        git push

  deploy:
    needs: update-data
    runs-on: ubuntu-latest
    
    permissions:
      pages: write
      id-token: write
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: main
    
    - name: Setup Pages
      uses: actions/configure-pages@v4
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./src
    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
